name: go test

on: [push]

jobs:
  build:
    runs-on: ubicloud-standard-2-ubuntu-2204-arm
    steps:
      - uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"
          cache: false
      - run: go test
